## The main function of SSP extraction process.
## The parameter of stoppingClusters is the stopping clustering results generated by DBSCAN;
## The parameter of radius here is the eps defined during the clustering process
stopPointsSampling<-function(stoppingClusters,radius) {
  clusterIDs<-unique(stoppingClusters[,"clusterindex"]);
  end=length(clusterIDs);
  result<- data.frame(Longitude=numeric(),Latitude=numeric());
  for(i in 1:end) {
    id=clusterIDs[i];
    clusterData<-stoppingClusters[stoppingClusters$clusterindex==id,];
    sample_num<-sampleNumberEstimate(clusterData,radius);
    sampledPoints<-samplePointsFromData(clusterData,sample_num,radius);
    result<-rbind(result,sampledPoints);
  }
  return(result);
}
## Sample points from stopping clusters such that every sampled point is far enough from other sampled points
samplePointsFromData<-function(data,sample_num,radius) {
  result<- sampledPoint<-data[sample(nrow(data),1),2:3];
  count=1;
  while(count<sample_num) {
    sampledPoint<-data[sample(nrow(data),1),2:3];
    end=nrow(result);
    nearFlag=FALSE;
    for(i in 1:end) {
      if(gpsDistance(result[i,],sampledPoint)<radius) {
        nearFlag=TRUE;
        break;
      }     
    }
    if(nearFlag) {
      next;
    } else {
      count=count+1;
      result<-rbind(result,sampledPoint);
    }
  }
  return(result);
}
## Estimate the number of points to be sampled
sampleNumberEstimate<-function(clusterPoints, radius) {
  min_x<-min(clusterPoints[,"Latitude"]);   #downmost point
  max_x<-max(clusterPoints[,"Latitude"]);   #upmost point
  min_y<-min(clusterPoints[,"Longitude"]);  #rightmost point
  max_y<-max(clusterPoints[,"Longitude"]);  #leftmost point
  areaEstimate<-(max_x-min_x)*(max_y-min_y);
  numberEstimate<-floor(areaEstimate/(pi*radius^2))+1;
  if(areaEstimate==0) {
    numberEstimate=max((max_x-min_x),(max_y-min_y))/radius+1;
  }
    return(numberEstimate);
}